### Get All Courses
GET http://localhost:3333/courses

### Search by Course
# http://localhost:3333/courses?search=React
http://localhost:3333/courses?orderBy=title

### Get Course by Id
GET http://localhost:3333/courses/a2b3f3ef-45ae-4c78-92eb-5898af7a2fcf

### Create a course
POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de PHP"
}