### Get All Courses
GET http://localhost:3333/courses

### Search by Course
# http://localhost:3333/courses?search=React
http://localhost:3333/courses?orderBy=title

### Get Course by Id
GET http://localhost:3333/courses/ff01f051-53de-4ae1-964c-3f1abee3b9fd

### Create a course
POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de PHP"
}